server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: llm-transformer
  profiles:
    active: default
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Transformer model configuration
transformer:
  vocabulary-size: 50257
  max-sequence-length: 1024
  embedding-dimension: 768
  num-layers: 12
  num-heads: 12
  feed-forward-dimension: 3072
  dropout-rate: 0.1
  layer-norm-epsilon: 1e-5
  activation-function: gelu

# Logging configuration
logging:
  level:
    com.maak.llm: INFO
    org.springframework: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    disable-swagger-default-url: true
  show-actuator: true

# CORS configuration
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Thread pool configuration
async:
  core-pool-size: 4
  max-pool-size: 8
  queue-capacity: 500

# Training configuration
training:
  learning-rate: 0.0001
  batch-size: 32
  epochs: 10
  max-sequence-length: 512
  weight-decay: 0.01
  gradient-clipping: 1.0
  warmup-steps: 4000
  save-every-steps: 1000
  evaluate-every-steps: 500
  data-path: "data/training"
  checkpoint-path: "checkpoints"
  use-gradient-accumulation: true
  accumulation-steps: 4
